
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND ASSIGN BOOL BREAK COLON COMMA CONST CONTINUE DIV DOT DOUBLE ELSE EQUAL F16 F32 F64 FLOAT FOR FUNC GENERICS GREATER GREATER_EQUAL HEXADECIMAL I16 I32 I8 ID IF IN INT INTERFACE LANGRBRACKET LBRACE LBRACKET LESS LESS_EQUAL LET LOGICAL_AND LOGICAL_NOT LOGICAL_OR LPAREN LSHIFT MINUS MOD MUL NOT NOT_EQUAL OR OUT PLUS RANGRBRACKET RBRACE RBRACKET RETURN RETURNTYPE RPAREN RSHIFT SAMPLER SEMICOLON STRING STRUCT TYPE U16 U32 U8 VOID WHILE XOR refexpression : expression PLUS termexpression : expression MINUS termexpression : termterm : term MUL factorterm : term DIV factorterm : factorfactor : INTfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'INT':([0,5,6,7,8,9,],[4,4,4,4,4,4,]),'LPAREN':([0,5,6,7,8,9,],[5,5,5,5,5,5,]),'$end':([1,2,3,4,11,12,13,14,15,],[0,-3,-6,-7,-1,-2,-4,-5,-8,]),'PLUS':([1,2,3,4,10,11,12,13,14,15,],[6,-3,-6,-7,6,-1,-2,-4,-5,-8,]),'MINUS':([1,2,3,4,10,11,12,13,14,15,],[7,-3,-6,-7,7,-1,-2,-4,-5,-8,]),'RPAREN':([2,3,4,10,11,12,13,14,15,],[-3,-6,-7,15,-1,-2,-4,-5,-8,]),'MUL':([2,3,4,11,12,13,14,15,],[8,-6,-7,8,8,-4,-5,-8,]),'DIV':([2,3,4,11,12,13,14,15,],[9,-6,-7,9,9,-4,-5,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,5,],[1,10,]),'term':([0,5,6,7,],[2,2,11,12,]),'factor':([0,5,6,7,8,9,],[3,3,3,3,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','parser.py',21),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','parser.py',26),
  ('expression -> term','expression',1,'p_expression_term','parser.py',31),
  ('term -> term MUL factor','term',3,'p_term_mul','parser.py',36),
  ('term -> term DIV factor','term',3,'p_term_div','parser.py',41),
  ('term -> factor','term',1,'p_term_factor','parser.py',46),
  ('factor -> INT','factor',1,'p_factor_num','parser.py',51),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','parser.py',56),
]
